config/routes.rb
Rails.application.routes.draw do
  post 'sign_up', to: 'sessions#create'
  get 'sign_in', to: 'sessions#new'
  delete 'sign_out', to: 'sessions#destroy'


  get 'page/index'
  root 'page#index'

  resources :users do
    collection do
      get :sign_in, to: redirect('sign_in')
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  has_secure_password

  def appear(on: nil)
    update(appeared: true, appeared_on: on)
    ActionCable.server.broadcast "AppearanceChannel", { event: 'appear', user_id: self.id, room: appeared_on }
  end

  def disappear
    update(appeared: false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id] 
  end


  def user_signed_in?
    redirect_to sign_in_path and return unless session[:user_id] && session[:user_id] == current_user.id 
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      cookies.signed[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    cookies.signed[:user_id] = nil
    redirect_to sign_in_path
  end 
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:create, :new]
  before_action :user_signed_in?, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    end
  end
    
  def show
  end

    private
    def user_params
      params.require(:user).permit(:email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorldActionCable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class= 'container'>
      <%= render 'users/status' %>
      <main data-appearing-on=<%=request.path%>>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/page/index.html.erb
<h1>Action Cabel Example</h1>
<div id='messages'></div>

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.button :submit

app/views/users/_status.html.slim
.container-fluid.mt-3
  .row.justify-content-end
    button type='button' class='btn btn-primary' id='active_users'
      | Online
      #active_user_badge

app/views/users/new.html.slim
= render 'form'

app/views/users/show.html.slim
table.table.table-striped
  thead
    tr
      th scope="col"  User
      th scope="col"  Email
      th scope="col"  Sign Out
  tbody
    tr
      th scope="row"
        = @user.id
      td
        = @user.email
      td
        = link_to 'Sign Out', sign_out_path, method: :delete